from enum import StrEnum


class WorkflowState(StrEnum):
    INITIALIZING = "INITIALIZING"
    RUNNING = "RUNNING"
    FAILING = "FAILING"
    CANCELLING = "CANCELLING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class TaskState(StrEnum):
    PENDING = "PENDING"
    RUNNABLE = "RUNNABLE"
    RUNNING = "RUNNING"
    RETRY_WAIT = "RETRY_WAIT"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AttemptState(StrEnum):
    CLAIMED = "CLAIMED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class FailureCategory(StrEnum):
    CLIENT_INPUT = "CLIENT_INPUT"
    VALIDATION = "VALIDATION"
    DOMAIN_CONFLICT = "DOMAIN_CONFLICT"
    DOMAIN_EXECUTION = "DOMAIN_EXECUTION"
    TIME_BASED = "TIME_BASED"
    WORKER_AVAILABILITY = "WORKER_AVAILABILITY"
    SYSTEM_TRANSIENT = "SYSTEM_TRANSIENT"
    SYSTEM_PERMANENT = "SYSTEM_PERMANENT"
    CONCURRENCY = "CONCURRENCY"
    INTEGRITY = "INTEGRITY"
    UNKNOWN_OUTCOME = "UNKNOWN_OUTCOME"
    SECURITY = "SECURITY"


class ProcessLifecycle(StrEnum):
    SERVING = "SERVING"
    DRAINING = "DRAINING"
    TERMINATING = "TERMINATING"


class PublicPermission(StrEnum):
    DEFINITIONS_READ = "definitions:read"
    DEFINITIONS_WRITE = "definitions:write"
    EXECUTIONS_READ = "executions:read"
    EXECUTIONS_START = "executions:start"
    EXECUTIONS_CANCEL = "executions:cancel"


class PrincipalType(StrEnum):
    PUBLIC_CLIENT = "PUBLIC_CLIENT"
    WORKER = "WORKER"
